export const GET_SOLAR = "GET_SOLAR";
export const GET_SOLAR_SUCCESS = "GET_SOLAR_SUCCESS";
export const GET_CONSUMED = "GET_CONSUMED";
export const GET_CONSUMED_SUCCESS = "GET CONSUMED_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";